import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
  Box,
  Button,
  Divider,
  Text,
  Center,
  useColorMode,
  useColorModeValue
} from '@chakra-ui/react';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <>
      <Head>
        <title>Dhairya Gupta - Developer, creator, student.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box w="100%" p={4}>
        <Text fontWeight={700} fontSize={30} fontFamily="Inter">
          {"Hi, I'm Dhairya Gupta"}
        </Text>
        <Text
          maxW="676px"
          fontSize={16}
          color={useColorModeValue('gray.600', 'gray.400')}
        >
          {
            "I'm a developer, creator, and student. I spend a portion of my free time coding and writing. This is a place where you can see both"
          }
        </Text>
      </Box>

      <footer>
        <Divider />
      </footer>
    </>
  );
}
